onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /pipelinecounter_tb/reset
add wave -noupdate /pipelinecounter_tb/clock
add wave -noupdate -divider {Counter output}
add wave -noupdate -radix unsigned -childformat {{/pipelinecounter_tb/countOut(19) -radix unsigned} {/pipelinecounter_tb/countOut(18) -radix unsigned} {/pipelinecounter_tb/countOut(17) -radix unsigned} {/pipelinecounter_tb/countOut(16) -radix unsigned} {/pipelinecounter_tb/countOut(15) -radix unsigned} {/pipelinecounter_tb/countOut(14) -radix unsigned} {/pipelinecounter_tb/countOut(13) -radix unsigned} {/pipelinecounter_tb/countOut(12) -radix unsigned} {/pipelinecounter_tb/countOut(11) -radix unsigned} {/pipelinecounter_tb/countOut(10) -radix unsigned} {/pipelinecounter_tb/countOut(9) -radix unsigned} {/pipelinecounter_tb/countOut(8) -radix unsigned} {/pipelinecounter_tb/countOut(7) -radix unsigned} {/pipelinecounter_tb/countOut(6) -radix unsigned} {/pipelinecounter_tb/countOut(5) -radix unsigned} {/pipelinecounter_tb/countOut(4) -radix unsigned} {/pipelinecounter_tb/countOut(3) -radix unsigned} {/pipelinecounter_tb/countOut(2) -radix unsigned} {/pipelinecounter_tb/countOut(1) -radix unsigned} {/pipelinecounter_tb/countOut(0) -radix unsigned}} -radixshowbase 0 -subitemconfig {/pipelinecounter_tb/countOut(19) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(18) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(17) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(16) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(15) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(14) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(13) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(12) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(11) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(10) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(9) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(8) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(7) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(6) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(5) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(4) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(3) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(2) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(1) {-height 17 -radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(0) {-height 17 -radix unsigned -radixshowbase 0}} /pipelinecounter_tb/countOut
add wave -noupdate -format Analog-Step -height 100 -max 1250000.0 -radix unsigned -childformat {{/pipelinecounter_tb/countOut(19) -radix unsigned} {/pipelinecounter_tb/countOut(18) -radix unsigned} {/pipelinecounter_tb/countOut(17) -radix unsigned} {/pipelinecounter_tb/countOut(16) -radix unsigned} {/pipelinecounter_tb/countOut(15) -radix unsigned} {/pipelinecounter_tb/countOut(14) -radix unsigned} {/pipelinecounter_tb/countOut(13) -radix unsigned} {/pipelinecounter_tb/countOut(12) -radix unsigned} {/pipelinecounter_tb/countOut(11) -radix unsigned} {/pipelinecounter_tb/countOut(10) -radix unsigned} {/pipelinecounter_tb/countOut(9) -radix unsigned} {/pipelinecounter_tb/countOut(8) -radix unsigned} {/pipelinecounter_tb/countOut(7) -radix unsigned} {/pipelinecounter_tb/countOut(6) -radix unsigned} {/pipelinecounter_tb/countOut(5) -radix unsigned} {/pipelinecounter_tb/countOut(4) -radix unsigned} {/pipelinecounter_tb/countOut(3) -radix unsigned} {/pipelinecounter_tb/countOut(2) -radix unsigned} {/pipelinecounter_tb/countOut(1) -radix unsigned} {/pipelinecounter_tb/countOut(0) -radix unsigned}} -radixshowbase 0 -subitemconfig {/pipelinecounter_tb/countOut(19) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(18) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(17) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(16) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(15) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(14) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(13) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(12) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(11) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(10) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(9) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(8) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(7) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(6) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(5) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(4) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(3) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(2) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(1) {-radix unsigned -radixshowbase 0} /pipelinecounter_tb/countOut(0) {-radix unsigned -radixshowbase 0}} /pipelinecounter_tb/countOut
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 240
configure wave -valuecolwidth 122
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1000
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 ns} {21 ms}
